### ISSUE TITLE
Distinguish “.NET Core Desktop Runtime” version from “.NET Core Runtime” as dependency while setup

### ISSUE THREAD

**Issue by Ni2Be** [dotnet/windowsdesktop#1363]
Hello, I hope this is the right place for my question:

We used to install “.NET Core Runtime” as a prerequisite in our wix-Setup. 
Now we introduced a new dependency to “.NET Core **Desktop** Runtime”.

Our Problem:
We use this registry key to get the version and then check if we need to update:
Root="HKLM" Key="SOFTWARE\dotnet\Setup\InstalledVersions\x64\sharedhost"

But “.NET Core **Desktop** Runtime” and “.NET Core Runtime” are both setting this key.
So if 3.1.11 “.NET Core Runtime” is installed our setup wont install the “Desktop” version.

Is there a key we could use or would you recommend a different way to check for the version and if “Desktop” is installed?

**Comment by RussKie** [comment]
@NikolaMilosavljevic is this something you could help with?

**Comment by Tyrrrz** [comment]
@Ni2Be

A more reliable way to detect installed runtimes is to run `dotnet --list-runtimes` programmatically and look for `Microsoft.WindowsDesktop.App` in standard output.

As a side note, I made a little package that replaces the default `exe` shim with a bootstrapper that just does downloads and installs .NET automatically: https://github.com/Tyrrrz/DotnetRuntimeBootstrapper

**Comment by molesmoke** [comment]
I was trying to achieve the same effect via the UpgradeCode, but it seems that it's not constant between the versions. For instance, checking in Orca:
WDR 5.0.6 (x86) - UpgradeCode: {2A9685EF-543B-6723-B828-8A65A3946333}
WDR 5.0.7 (x86) - UpgradeCode: {ACAEDB65-5BD1-4EE3-375E-D4768D61BF8E}

Is there a Microsoft recommendation to determine what this installed version is?

**Comment by rickbrew** [comment]
You can also use the `NETCoreCheck` utility. You can get it as an EXE (per-platform) with  https://www.nuget.org/packages/Microsoft.NET.Tools.NETCoreCheck.x64 . It can check for the runtime and for the WindowsDesktop runtime pack (and ASP.NET if you want).

The source is also at https://github.com/dotnet/deployment-tools/tree/main/src/clickonce/native/projects/NetCoreCheck if you prefer to inline it. You'll need to also include the UCRT DLLs for x86 and x64 (not needed for arm64).

This is what I use in my setup package for checking prerequisites for Paint.NET.

Note that the command-line syntax changed between 5.0 and 6.0 (preview only so far). I use the 6.0 preview builds.

**Comment by Ni2Be** [comment]
Oh I’m sorry, for some reason notifications on this were disabled. Thanks for all the answers 😊 
We went with a combination of checking registry values and parsing file-names. It’s pretty robust atm but we will definitely have a look on NETCoreCheck when we integrate 6.0
