### ISSUE TITLE
.NET Desktop Runtime 5.0.8 (ARM64) does not include .NET Runtime 5.0.8

### ISSUE THREAD

**Issue by rickbrew** [dotnet/windowsdesktop#1823]
As per https://dotnet.microsoft.com/download/dotnet/5.0 :

> The .NET Desktop Runtime enables you to run existing Windows desktop applications. **This release includes the .NET Runtime, you do not need to install it separately.**

However, if you install the ARM64 build, it does not include the .NET Runtime, e.g. `C:\Program Files\dotnet\dotnet.exe` doesn't exist. You just get `dotnet/shared/Microsoft.WindowsDesktop.App/*`

This works as expected on x86/x64.

**Comment by merriemcgaw** [comment]
@dreddy-work can you take point on getting this fixed for the next servicing release?

**Comment by dreddy-work** [comment]
> @dreddy-work can you take point on getting this fixed for the next servicing release?

@ryalanms  is on it.

**Comment by ryalanms** [comment]
@leecow :   The WindowsDesktop repo is not tracked in TacticsView, so we have been raising servicing bugs in Tactics or via email.  Can WindowsDesktop (and wpf-int, if possible) be added?  

(There is already a single-line PR out to include the Runtime in the WindowsDesktop runtime, but it missed the 5.0.9 window.)

**Comment by merriemcgaw** [comment]
Thanks guys, I should have double checked 😊

**Comment by leecow** [comment]
@timheuer - can you make the update?

**Comment by timheuer** [comment]
@leecow update made, `dotnet/WindowsDesktop` added and will start being picked up.  I couldn't find `wpf-int` and assume that is a non-public repo which wouldn't presently work...let me know if I need to think about that though.

**Comment by rickbrew** [comment]
So just to clarify, this will be fixed with the 5.0.10 release? (September, right?)

Thankfully I have a reasonable and simple workaround for now -- I just install both the Runtime and Desktop Runtime on arm64 as part of app setup.

**Comment by ryalanms** [comment]
> So just to clarify, this will be fixed with the 5.0.10 release? (September, right?)
> 
> Thankfully I have a reasonable and simple workaround for now -- I just install both the Runtime and Desktop Runtime on arm64 as part of app setup.

@rickbrew:  Yes, that is correct.  Unfortunately the fix did not make 5.0.9.

**Comment by RussKie** [comment]
Closing as .NET 5 has reached EOL
