### ISSUE TITLE
Determine branding for WindowsDesktop shared framework bundle installer

### ISSUE THREAD

**Issue by dagood** [dotnet/windowsdesktop#191]
This is what the Windows Desktop Runtime bundle installer UI looks like with my initial implementation, basically just replacing `.NET Core` with `Windows Desktop`. Initial questions:

1. Is `Microsoft Windows Desktop Runtime` the right name?
2. What should the description text be changed to?
3. What should/can we do about the overflow? 
   * An interesting wrinkle with fixing it is the `Alpha 1`/`Preview 9`/etc. prerelease label won't appear in the stable release, so if we fix it by e.g. decreasing font size, it would be pointlessly small at 3.0.0 RTM. I'm thinking it might make the most sense to verify it'll eventually work with RTM versioning and leave it.

![image](https://user-images.githubusercontent.com/12819531/62241193-5132d000-b39e-11e9-967e-d88bbbde1ba7.png)

Note that this has to loop through the loc process once we're done. I'll drive that.

@vatsan-madhavan @merriemcgaw @zsd4yr, thoughts?

/cc @dleeapho @leecow @ericstj

(Bundle implementation tracked at https://github.com/dotnet/core-setup/issues/6384.)

**Comment by RussKie** [comment]
Is there anything outstanding, or can we close this?

**Comment by dagood** [comment]
It looks like there's text now! 🎉 

![image](https://user-images.githubusercontent.com/12819531/113168952-be010c00-920a-11eb-9bdd-cb44168c8060.png)

/cc @NikolaMilosavljevic

**Comment by NikolaMilosavljevic** [comment]
> It looks like there's text now! 🎉

Yeah, that was fixed as part of 5.0 branding work: https://github.com/dotnet/windowsdesktop/pull/769

Closing this issue.
