### ISSUE TITLE
dotnet5 feeds should be removed from release/6.0* branches

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/windowsdesktop#1978]
The dotnet5 feeds are still listed in the repo's NuGet.config file in release/6.0* branches. These feeds shouldn't be used to construct the 6.0 product.

cc @mmitche

**Comment by dreddy-work** [comment]
@mmitche, can you confirm? I can help remove them.

**Comment by mmitche** [comment]
Yep they should be able to be removed.
