### ISSUE TITLE
Include .NET Core Runtime in WindowsDesktop bundle

### ISSUE THREAD

**Issue by dagood** [dotnet/windowsdesktop#20]
This is a clone of https://github.com/dotnet/core-setup/issues/8504. This feature will be implemented in Core-Setup pre-5.0, but it needs to be reimplemented in WindowsDesktop for 5.0+ because of the repo split.

Unfortunately, due to the split, the implementation will be more difficult here. We need some infra that will download the .NET Core Runtime MSIs and bundle them into the WindowsDesktop bundle installer.

> To run a .NET Core WPF/WinForms app, you need to install both the .NET Core Runtime and WindowsDesktop Runtime. (As well as the correct x86/x64 bitness.) This is unexpected and is a significant pain point when trying to deploy FDE WinForms and WPF apps.
> 
> This issue tracks the incremental step of including the .NET Core Runtime dependency in the installer bundle for the WindowsDesktop Runtime.
> 
> This will bring our current matrix of 4 installers needed to run WindowsDesktop apps:
> 
> |   | x64 | x86 |
> | --- | --- | --- |
> | .NET Core Runtime | x | x |
> | .NET Desktop Runtime | x | x |
> 
> down to 2:
> 
> |   | x64 | x86 |
> | --- | --- | --- |
> | .NET Desktop Runtime | x | x |

/cc @dleeapho @MichaelSimons

**Comment by zsd4yr** [comment]
Won't this version be dependent on the version of the runtime WPF/WinForms are built with?

**Comment by dagood** [comment]
Yeah, setting up a coherent parent dependency makes sense to me.

**Comment by zsd4yr** [comment]
> Yeah, setting up a coherent parent dependency makes sense to me.

Pardon the clarification -- @vatsan-madhavan will WPF continue to coherent parent depend its version of the runtime via WinForms? 
If not, then ensuring coherency of that dependency here may be sticky.

**Comment by vatsan-madhavan** [comment]
Yes, we will continue depending on WinForms to inform our runtime version. 

All WindowsDesktop pieces should have one controlling entity for the runtime version. WinForms is the lowest in layering - so that’s it.

**Comment by vatsan-madhavan** [comment]
This repo should also ingest runtime version via WimForms IMO.
