### ISSUE TITLE
Stale WinForms drop

### ISSUE THREAD

**Issue by AArnott** [dotnet/windowsdesktop#367]
I just downloaded the latest drop and it does not have the content of [this PR](https://github.com/dotnet/winforms/pull/2650) which completed two days ago. So either the dependencies aren't updating at all, or perhaps the drops just aren't built frequently.

**Comment by dagood** [comment]
The flow is blocked at WPF: https://github.com/dotnet/wpf/pull/2399. Official builds are working fine ATM, latest 3h ago: https://dev.azure.com/dnceng/internal/_build/results?buildId=476092&view=results

**Comment by RussKie** [comment]
Can we close this?
