### ISSUE TITLE
Wrong version in WindowsDesktop to NETCore.App dependency

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/windowsdesktop#368]
The latest full SDK from [core-sdk](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdotnetcli.blob.core.windows.net%2Fdotnet%2FSdk%2Fmaster%2Fdotnet-sdk-latest-win-x64.zip&data=02%7C01%7CVitek.Karas%40microsoft.com%7Cb22c9d84a0814c52b38808d7948f71a7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637141216131387998&sdata=U83iOsMj%2FstrjY%2FxZEJ%2F6WMnBY4NiPUUeYUzFLYWbko%3D&reserved=0) is internally inconsistent. The Microsoft.WindowsDesktop.App framework is version 5.0.0-alpha.1.20052.4 and in its runtime config it declares dependency on Microsoft.NETCore.App version 5.0.0-alpha.1.20052.4. But the zip contains Microsoft.NETCore.App version 5.0.0-alpha.1.19564.1. Which is a lower version and so trying to run any WPF/WinForms app on this runtime will fail because the reference from Microsoft.WindowsDesktop.App to Microsoft.NETCore.App won’t resolve.

Either we need to fix how the zip/installers are constructed to make sure that we never include newer version of WindowsDesktop then NETCore.App (but that could cause issues when trying to service just WindowsDesktop for example), or we need to fix the declared dependency in `.runtimeconfig.json` to point to the right version of NETCore.App.

Comment from @dagood :
I think the fix will be around here: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.SharedFramework.Sdk/targets/framework.sharedfx.targets#L71
using a different prop than SharedFrameworkNugetVersion (or allowing override), and having windowsdesktop populate it with the version of netcoreapp it depends on rather than its own version.

This is pretty important as currently the daily built from core-sdk can't run any WindowsDesktop apps due to this issue.

**Comment by RussKie** [comment]
I think this is somewhat related to the WPF issue with C++/CLR (https://github.com/dotnet/wpf/pull/2399#issuecomment-572241063).
We had a customised build that allowed WinForms and WPF to flow through, but we were pinned to a specific build of Core SDK. When Core SDK was renamed to Runtime, we got unpinned (unfortunately), and now all things are broken.

**Comment by dagood** [comment]
This should be fixed once the repo gets an arcade update (meshes with https://github.com/dotnet/windowsdesktop/pull/373), but the arcade update PR's been blocked for a while: https://github.com/dotnet/windowsdesktop/pull/236. I'll look at that within a few days. Might be a missing nuget feed based on the CI error message.

**Comment by dagood** [comment]
Confirmed this is fixed with the latest build! `Microsoft.WindowsDesktop.App` is `5.0.0-alpha.1.20067.4`, but the runtimeconfig contains `5.0.0-alpha1.19514.1`, matching the NETCoreApp laid down by the bundle installer.
