### ISSUE TITLE
The [...].versions.txt file in the NuGet packages says the commit comes from core-setup

### ISSUE THREAD

**Issue by dagood** [dotnet/windowsdesktop#4]
The `Microsoft.WindowsDesktop.App.versions.txt` files in the nupkgs say `core-setup <commit hash>`. This is defined in the shared framework tooling SDK, I missed it when implementing it:

https://github.com/dotnet/arcade/blob/663f5c6784b20b4c95ce92f0e4777af35b5eb771/src/Microsoft.DotNet.Build.Tasks.SharedFramework.Sdk/targets/framework.dependency.targets#L112

The obvious fix is to change that side to take an optional property to pick the repo name, and a change in dotnet/windowsdekstop to set it to `windowsdesktop`.

This file has no immediate infrastructure use, so this doesn't seem critical. However, people still may read it and would be misled.

**Comment by RussKie** [comment]
@dagood is this still a thing?

**Comment by dagood** [comment]
Problem still exists in: https://www.nuget.org/packages/Microsoft.WindowsDesktop.App.Runtime.win-x64/3.1.13
Problem is fixed in: https://www.nuget.org/packages/Microsoft.WindowsDesktop.App.Runtime.win-x64/5.0.4

Seems like a very low priority to me. 😄

/cc @NikolaMilosavljevic

**Comment by RussKie** [comment]
Would this issue belong to the Arcade repo? I can't find "core-setup" string in this repo.

**Comment by NikolaMilosavljevic** [comment]
> Would this issue belong to the Arcade repo? I can't find "core-setup" string in this repo.

We'll still need an issue in dotnet/windowsdesktop to set the new property. Infra change to use the new property during nuget packaging would be in Arcade. Arcade change should set a default value if property is not defined.

**Comment by dreddy-work** [comment]
@NikolaMilosavljevic, Is this implemented on Arcade and can take the new string if we add in the desktop repo?

**Comment by NikolaMilosavljevic** [comment]
> @NikolaMilosavljevic, Is this implemented on Arcade and can take the new string if we add in the desktop repo?

Not sure, there were several infra refactorings in 2021 and 2022. If this still reproes feel free to move the issue to `arcade`.
