### ISSUE TITLE
[infra] Azdo git mirror has conflict in fast forward branch release/6.0-installers

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/windowsdesktop#4453]
The [GH branch release/6.0-installers](https://github.com/dotnet/windowsdesktop/tree/release/6.0-installers) is supposed to be mirrored into [internal Azdo branch release/6.0-installers](https://dev.azure.com/dnceng/internal/_git/dotnet-windowsdesktop?version=GBrelease%2F6.0-installers) **as fast forward**

Unfortunately there are extra commits in the internal branch, which prevents the automation to finish the job.

The resolution is probably to force push from azdo to github. Please review if there are any unpublished security fixes first.

**Comment by mmitche** [comment]
Stale branch, closing
