### ISSUE TITLE
MSI UpgradeCode for Windows Dekstop runtime installer changes with each minor version

### ISSUE THREAD

**Issue by arknu** [dotnet/windowsdesktop#4510]
The MSI UpgradeCode changes for each minor version of the .NET Windows Desktop Runtime installer. See for instance this comparison between 8.0.3 and 8.07:
![image](https://github.com/user-attachments/assets/e03e7c78-fbd9-40b6-8c70-351435daaa00)

This is a violation of standard MSI authoring practice which states that this code should never be changed - and certainly not between minor versions. In the case of .NET Windows Desktop Runtime I would think it appropriate to have a different UpgradeCode for each major version, since multiple versions can be installed side-by-side and they need different IDs for Windows Installer to allow that.

But different UpgradeCodes for minor versions should never happen, since only one can be installed at any time.

This bug makes it much harder to detect whether the desktop runtime is installed. Rather than just doing a standard MSI detection, I now have to resort to searching through the registry.

The .NET Hosting Bundle installer does not suffer from this issue, it is only the .NET Windows Desktop Runtime installer that exhibits this strange behavior.

**Comment by merriemcgaw** [comment]
I am going to close this issue as by-design as @joeloff has described.
