### ISSUE TITLE
FrameworkReference Microsoft.WindowsDesktop.App.WindowsForms Incorrectly Includes WindowsFormsIntegration.dll

### ISSUE THREAD

**Issue by lonitra** [dotnet/windowsdesktop#4789]
In .NET 9 we are experiencing issues where when adding `<FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" />` in a winUI project and building, it tries to resolve System.Xaml even though WinForms does not reference Xaml. This is occurring because we had changed `WindowsFormsIntegration.dll` to have [profile with WPF and WindowsForms](https://github.com/dotnet/windowsdesktop/blob/main/src/windowsdesktop/src/sfx/Directory.Build.props#L59) causing `ResolveAssemblyReferences` target to include WindowsFormsIntegration.dll in references thus pulling this .dll in even though it is only intended when no profile is specified i.e. `UseWindowsForms` and `UseWPF` is true as indicated in https://github.com/dotnet/wpf/blob/bbfc24fd13804a191e20064acd599b0a359092df/packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props#L45-L46. In .NET 8 there was [no profile attribute](https://github.com/dotnet/windowsdesktop/blob/release/8.0/src/windowsdesktop/src/sfx/Microsoft.WindowsDesktop.App.Ref.sfxproj#L34) for this dll.

We had made this update as part of https://github.com/dotnet/windowsdesktop/pull/4227 to support runtime pack respecting profiles when publish self contained winforms/wpf app (https://github.com/dotnet/sdk/issues/37088)

Repro project: [App11.zip](https://github.com/user-attachments/files/17838357/App11.zip)

Repro steps:
1. unzip and build project via command line with `msbuild -p:platform=x64 -bl`
2. Observe failure about trying to resolve System.Xaml
3. If we look at the binlog, failure occurs under `MarkupCompilePass1` target, specifically in `CompileXaml` task. For that task, if we look at Parameters > ReferenceAssemblies we can see WindowsFormsIntegration.dll
4. If we search `ReferencePath` (this is what the ReferenceAssemblies parameter is in the targets file), we can see WindowsFormsIntegration.dll first gets added in `ResolveAssemblyReferences` target, specifically `ResolveAssemblyReference` task
5. In .NET 8 binlog which is included in zip observe WindowsFormsIntegration.dll is not included in `ReferencePath`

More info: This was originally reported via https://github.com/dotnet/maui/issues/25883 but scenario can be simplified which is what the repro project demonstrates

**Comment by lonitra** [comment]
Reopening for pending port to 9.0

**Comment by lonitra** [comment]
Fix will be available in 9.0.1 release

**Comment by nicop85** [comment]
@lonitra do you know the estimated date for 9.0.1 release?

**Comment by lonitra** [comment]
9.0.1 should be available January 14
