### ISSUE TITLE
Remove leftover code after the migration from the Core-Setup repo

### ISSUE THREAD

**Issue by dagood** [dotnet/windowsdesktop#5]
This repo took a lot of code from Core-Setup to get started. A lot of it doesn't apply here, and should be removed for maintainability:

* There are dependencies in `Version.Details.props`, and `Versions.props` that aren't used.
  * This may also affect how WindowsDesktop appears in build graphs and reporting tools. Most important to remove this, I believe.
* There are references to non-Windows platforms that aren't applicable in this repo. I removed a little of this, but there's a decent amount left.
* References to NETCoreApp, and infra supporting NETCoreApp builds that isn't necessary to build WindowsDesktop.
* Dead code. Core-Setup itself wasn't particularly clean when the code was ported over, so there may be some infra that serves no purpose.
* Unused `.gitignore` entries.
* Properties that duplicate Arcade SDK properties.
  * The dependency on the old properties by the sharedfx tooling was fixed by https://github.com/dotnet/arcade/pull/4254.

Some of this can be difficult to remove because it needs to be tested with clean builds, and on all platforms. It may not be so bad in this repo because it only runs win-x64 and win-x86.

**Comment by ViktorHofer** [comment]
Completed with https://github.com/dotnet/windowsdesktop/commit/8bd3e3cdee6bbf39752848ed298df16222627302
