### ISSUE TITLE
Port change from Core-Setup to rely on Arcade for dotnetcli blob storage publishing

### ISSUE THREAD

**Issue by dagood** [dotnet/windowsdesktop#533]
See https://github.com/dotnet/core-sdk/pull/6473#issuecomment-589389674

This repo needs to port https://github.com/dotnet/core-setup/pull/8426 to be more flexible with new channels being added.

**Comment by merriemcgaw** [comment]
@AdamYoblick can you take a look at this for us?

**Comment by AdamYoblick** [comment]
Yep, it’s on my list :)

________________________________

**Comment by mmitche** [comment]
@AdamYoblick What's the ETA on the port of this change?

**Comment by AdamYoblick** [comment]
I’m not sure, I’ve been working on winforms designer stuff. @Merrie McGaw<mailto:Merrie.McGaw@microsoft.com> , would you like me to re-prioritize?

________________________________

**Comment by merriemcgaw** [comment]
Either you or @RussKie would be great. We can also ask @ryalanms to help too.

**Comment by AdamYoblick** [comment]
I attempted to port the change, PR is at #768 . I'm not really sure what I was doing here, so it was just a straight port. 😄
