### ISSUE TITLE
WindowsDesktop installer doesn't install a distinct registry key (5.0+)

### ISSUE THREAD

**Issue by dagood** [dotnet/windowsdesktop#541]
The WD installer places a registry key for `Microsoft.NETCore.App`, not `Microsoft.WindowsDesktop.App`. E.g. a recent daily build:

Key: `SOFTWARE\dotnet\Setup\InstalledVersions\x64\sharedfx\Microsoft.NETCore.App`
Name: `5.0.0-preview.2.20125.2`
Value: `#1`

I filed https://github.com/dotnet/runtime/issues/32836 tracking potentially fixing this in 3.1. (Core-Setup servicing issues are tracked in dotnet/runtime.) It has more details how this flow probably happens. Basically, a bad default:

https://github.com/dotnet/windowsdesktop/blob/17106acc62ad7194e032f1b1fd1511033069b515/Directory.Build.props#L68

@NikolaMilosavljevic

**Comment by merriemcgaw** [comment]
@NikolaMilosavljevic m @dagood, is this something acquisition should be doing or is this something for Winforms/wpf team?
