### ISSUE TITLE
RollForward from 3.1 to 5.0 fails to load System.Drawing.Common, System.CodeDom

### ISSUE THREAD

**Issue by Shyam-Gupta** [dotnet/windowsdesktop#577]
**Repro Steps:**

1. Create a WinForms .NET Core 3.1 application 
2. Declare a variable of type `System.Drawing.Font` somewhere in the code
3. Build the application with `rollForward` set to `major`
4. Run the application on a machine having no 3.1 SDK but having latest .NET Core 5.0 SDK installed 

**Result:**
System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'System.Drawing.Common, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)

I found similar issue with `System.CodeDom`. 

Product version of both these dlls is 5.0.0-alpha1.19512.1. Perhaps these dlls need to be updated. ?

**Comment by dagood** [comment]
The set of subscriptions targeting this repo are strangely spotty:

```
https://github.com/dotnet/arcade (.NET Eng - Latest) ==> 'https://github.com/dotnet/windowsdesktop' ('master')
https://github.com/dotnet/runtime (.NET 5 Preview 2) ==> 'https://github.com/dotnet/windowsdesktop' ('release/5.0-preview2')
https://github.com/dotnet/wpf (.NET Core 5 Dev) ==> 'https://github.com/dotnet/windowsdesktop' ('master')
https://github.com/dotnet/wpf (.NET 5 Preview 1) ==> 'https://github.com/dotnet/windowsdesktop' ('release/5.0-preview1')
https://github.com/dotnet/wpf (.NET 5 Preview 2) ==> 'https://github.com/dotnet/windowsdesktop' ('release/5.0-preview2')
```

But also Version.Details.xml hasn't been updated, example:

https://github.com/dotnet/windowsdesktop/blob/7aafc9bba6521a60973e43672a4e4cd121bba1be/eng/Version.Details.xml#L15-L16

**Comment by dagood** [comment]
> ~But also Version.Details.xml hasn't been updated for consolidation~

I got this backwards--this should be updated *by* the Maestro++ auto-update once one happens. Updates are based on package ID (artifact name) alone.

**Comment by merriemcgaw** [comment]
@dagood @Shyam-Gupta  - is this good now that we're updating dependencies properly, or is there something else that needs to be done.

**Comment by RussKie** [comment]
Presume resolved
