### ISSUE TITLE
Please enable SDL validation (policheck, sourcelink, etc)

### ISSUE THREAD

**Issue by AdamYoblick** [dotnet/windowsdesktop#619]
Per Vivek's email, please enable SDL validation when calling post-build.yml from publish.yml.

- See https://github.com/dotnet/winforms/blob/4ac79a93f385b189ffbec42fc73329b5acbb52f1/eng/ci.yml#L141 for what winforms passes into the SDL validation.
- See https://dnceng.visualstudio.com/internal/_library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=66&path=DotNet-Winforms-SDLValidation-Params for the variables used in the winforms call

We probably need to make a new variable group (or hardcode the values in windowsdesktop).
- We probably need a new tsaBugAreaPath (I don't have access to create a new path in devdiv)
- tsaCodebaseAdmin should be Davis?
- tsaCodeBaseName should be WindowsDesktop
- tsaNotificationEmail should be something new (maybe a DL that includes both winforms and wpf?)
- tsaRepositoryName should be WindowsDesktop

/cc: @merriemcgaw @vivmishra @vatsan-madhavan

**Comment by vivmishra** [comment]
Yes, the second statement does not apply to 2.1 -- we should fix it by conditionally removing it.

**Comment by AdamYoblick** [comment]
I'm assigning this to myself as I'm going to do this work.

**Comment by merriemcgaw** [comment]
@merriemcgaw to confirm the internal path creation for issues to be filed.

**Comment by AdamYoblick** [comment]
This work is now done via https://github.com/dotnet/windowsdesktop/pull/1017.

SDL PER BUILD is configured, but DISABLED (identical to winforms repo, this was the ask from dnceng). 
SDL on .net core product NIGHTLY and RELEASE runs is enabled, matches all other repos.
