### ISSUE TITLE
Produce WindowsDesktop-only package zip file

### ISSUE THREAD

**Issue by mthalman** [dotnet/windowsdesktop#716]
Currently the Microsoft.WindowsDesktop.App package is only available through the .exe installer or via its inclusion in the SDK zip file.  But there is a need for the ability to construct a .NET installation piecemeal.  This is related to https://github.com/dotnet/sdk/issues/11211.

A scenario where this would be used is with Docker images.  As part of the changes in https://github.com/dotnet/dotnet-docker/issues/1351 and https://github.com/dotnet/dotnet-docker/issues/1814, the SDK image will now be based on the ASP.NET image, which itself is based on the runtime image.  This kind of layering means that each framework will be installed individually.  The runtime image installs Microsoft.NETCore.App and `dotnet.exe`.  The ASP.NET image builds on top of the runtime image by also installing Microsoft.AspNetCore.App.  The SDK image builds on top of the ASP.NET image by also installing the SDK and Microsoft.WindowsDesktop.App.  This layered approach requires that the Microsoft.WindowsDesktop.App be made available as a separate archive file so it can be retrieved individually.

The proposal is to produce a zip file that contains only the Microsoft.WindowsDesktop.App folder.

**Comment by vatsan-madhavan** [comment]
Have you looked at https://dotnetcli.blob.core.windows.net/dotnet/WindowsDesktop/<version>/windowsdesktop-runtime-<version>-<rid>.zip

For e.g., 
https://dotnetcli.blob.core.windows.net/dotnet/WindowsDesktop/5.0.0-preview.4.20209.2/windowsdesktop-runtime-5.0.0-preview.4.20209.2-win-x64.zip

**Comment by mthalman** [comment]
Ah perfect.  Yes, that's exactly what's needed.  I just assumed it didn't exist because there was no checksum listed for it (e.g. https://dotnetcli.blob.core.windows.net/dotnet/checksums/3.1.3-sha.txt).  That's a separate issue I guess.
