### ISSUE TITLE
Checksum for released zip archive file not listed in checksum list

### ISSUE THREAD

**Issue by mthalman** [dotnet/windowsdesktop#719]
The release notes for each release link to a checksum file that lists the checksums for all the released files.  Example: the [3.1.3 release notes](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.3/3.1.3.md) reference this [checksum file](https://dotnetcli.blob.core.windows.net/dotnet/checksums/3.1.3-sha.txt).  The checksums listed do not include the WindowsDesktop runtime zip file.  The exe is listed, but not the zip file.  This should be added.

**Comment by RussKie** [comment]
I checked the [latest 3.1 release page](https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1.13/3.1.13.md), and it doesn't look like we provide zip archives, hence no shas.
