### ISSUE TITLE
ARM64 WindowsDesktop Runtime pack's PlatformManifest is a superset of shipped assets

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/windowsdesktop#770]
Currently, the ARM64 runtime pack has a PlatformManifest that list assets we don't ship in such a package. The package only contains WinForms bits, and this is correctly reflected in the RuntimeList. The PlatformManifest however lists all the assets. This will result in a publish thinking the shared framework has assets it doesn't have. This might result in a runtime "File Not Found" exception for a published framework-dependent app.

**Comment by RussKie** [comment]
@hoyosjs is this still a thing?
