### ISSUE TITLE
Signing validation failing

### ISSUE THREAD

**Issue by mmitche** [dotnet/windowsdesktop#882]
https://dev.azure.com/dnceng/internal/_build/results?buildId=697772&view=logs&s=3df7d716-4c9c-5c26-9f45-11f62216640d&j=0a6c679f-72be-5867-422e-acb741a068a3

Official builds have been failing since https://dev.azure.com/dnceng/internal/_git/dotnet-windowsdesktop/commit/2595fea55907e19b621d24258470639a4428e5a6?refName=refs%2Fheads%2Fmaster

**Comment by ryalanms** [comment]
I'm looking at this now. 

All the assemblies failing sign validation are runtime assemblies, not WPF assemblies.  This appeared after a version update to 5.0.0-preview.7.20311.2. 

```
System.Diagnostics.PerformanceCounter.dll [Error] HRESULT: 800b0100 (No signature was present in the subject)
System.DirectoryServices.dll [Error] HRESULT: 800b0100 (No signature was present in the subject)
System.Drawing.Common.dll [Error] HRESULT: 800b0100 (No signature was present in the subject)
System.IO.FileSystem.AccessControl.dll [Error] HRESULT: 800b0100 (No signature was present in the subject)
System.IO.Packaging.dll [Error] HRESULT: 800b0100 (No signature was present in the subject)
System.Resources.Extensions.dll [Error] HRESULT: 800b0100 (No signature was present in the subject)
System.Security.AccessControl.dll [Error] HRESULT: 800b0100 (No signature was present in the subject)
System.Security.Cryptography.Cng.dll [Error] HRESULT: 800b0100 (No signature was present in the subject)
System.Security.Cryptography.Pkcs.dll [Error] HRESULT: 800b0100 (No signature was present in the subject)
System.Security.Cryptography.ProtectedData.dll [Error] HRESULT: 800b0100 (No signature was present in the subject)
System.Security.Cryptography.Xml.dll [Error] HRESULT: 800b0100 (No signature was present in the subject)
System.Security.Permissions.dll [Error] HRESULT: 800b0100 (No signature was present in the subject)
System.Security.Principal.Windows.dll [Error] HRESULT: 800b0100 (No signature was present in the subject)
System.Threading.AccessControl.dll [Error] HRESULT: 800b0100 (No signature was present in the subject)
System.Windows.Extensions.dll [Error] HRESULT: 800b0100 (No signature was present in the subject)
``

**Comment by mmitche** [comment]
Ahh. @ViktorHofer can you confirm this is fixed in new builds?

**Comment by mmitche** [comment]
@ryalanms Also, windowsdesktop is not currently signing its binaries, likely due to the same issue in runtime:

https://github.com/dotnet/runtime/pull/38104#pullrequestreview-435135282

**Comment by safern** [comment]
> Ahh. @ViktorHofer can you confirm this is fixed in new builds?

I can confirm this is fixed in new builds. I ran signing validation with the produced drop from the last official build and it succeeded:

```
No signing issues found
Total Time: 00:06:14.2232334
Total Files: 14079, Signed: 9343, Unsigned: 0, Skipped: 4636, Excluded: 100, Skipped & Excluded: 0
```

**Comment by ryalanms** [comment]
All the changes have now flowed from dotnet/wpf.  To fix the signing problem with WindowsDesktop, I assume the ItemGroup in Signing.props needs to be wrapped in a target, similar to https://github.com/dotnet/runtime/pull/38104/files#diff-3f0380cc81441e712c5eba1d7b77e649R15.  Is that sufficient?

**Comment by ryalanms** [comment]
This is fixed.  Thanks.
